Update to Pasta to make it possible to run it from python 3 (with typ…
google/pasta pull request #86
Opened 2020-12-07 19:55 UTC by bronevet-abc

…e checking, etc.) and have it parse either python 2 or 3.

Notes:
- I've introduced variable py_ver, set to either 'PY27' or 'PY3'. We probably want to replace it with a dict {major: #, minor: #} or something like that.
- I've had to wrap a bunch of code within function calls that introduce py_ver into existing files. It causes artificially many change lines according to Critique and may look a bit weird but it seems to be the simplest way to introduce this detail within the context of the testing framework.
- I had to mutilate the check for Python > 3.5 to make it work for now but we'll correct it once we decide how to describe Python versions.
- Fixed a few bugs in the code:
  - Case like 'globals a,b,c' where the first identifier appears again in the list.
  - Support for ur prefix for Python 2 string literals

2021-01-13 17:38 UTC, soupytwist requested changes
I left a lot of suggestions -- not sure how easy it is to incorporate these with GH's UI, hopefully it helps. Most of it is formatting, but please read. Overall looks good! I do want to make sure that it can still be used without ever specifying a python version (using the default `sys.version_info[:2]`).

2021-01-13 17:38 UTC, soupytwist commented on pasta/base/annotate.py
> +import typed_ast
Remove `ast` import?

2021-01-13 17:38 UTC, soupytwist commented on pasta/base/annotate.py
> +                 statement=False):
```suggestion
def _gen_wrapper(f, scope=True, prefix=True, suffix=True, max_suffix_lines=None,
                 semicolon=False, comment=False, statement=False):
```

2021-01-13 17:38 UTC, soupytwist commented on pasta/base/annotate.py
> +            default='\n' if statement else '')
```suggestion
        self.suffix(node, max_lines=max_suffix_lines, semicolon=semicolon,
                    comment=comment, default='\n' if statement else '')
```

2021-01-13 17:38 UTC, soupytwist commented on pasta/base/annotate.py
> +      statement=True)
```suggestion
  return _gen_wrapper(f, scope=False, max_suffix_lines=1, semicolon=True,
                      comment=True, statement=True)
```

2021-01-13 17:38 UTC, soupytwist commented on pasta/base/annotate.py
> +    # class BaseVisitor(ast.NodeVisitor):
```suggestion
```

2021-01-13 17:38 UTC, soupytwist commented on pasta/base/annotate.py
> +    This class has a dual-purpose. It is implemented (in this file) for
Please fix text wrapping

2021-01-13 17:38 UTC, soupytwist commented on pasta/base/annotate.py
> +    This class has a dual-purpose. It is implemented (in this file) for
(here and elsewhere in this file)

2021-01-13 17:38 UTC, soupytwist commented on pasta/base/annotate.py
> +               default=''):
```suggestion
      def suffix(self, node, max_lines=None, semicolon=False, comment=False,
             default=''):
```

2021-01-13 17:38 UTC, soupytwist commented on pasta/base/annotate.py
> +              default_parens=False):
```suggestion
    def scope(self, node, attr=None, trailing_comma=False, default_parens=False):
```

2021-01-13 17:38 UTC, soupytwist commented on pasta/base/annotate.py
> +        if alias != node.names[-1]:
Do you remember why this is needed? Alias is an ast node, isn't it?

2021-01-13 17:38 UTC, soupytwist commented on pasta/base/annotate.py
> +          default='.' * node.level + (node.module or ''))
```suggestion
      self.attr(node, 'module', module_pattern, deps=('level', 'module'),
                default='.' * node.level + (node.module or ''))
```

2021-01-13 17:38 UTC, soupytwist commented on pasta/base/annotate.py
> +          separate_before=True)
```suggestion
      self.attr(node, 'else', [self.ws, 'else', self.ws], default=' else ',
                separate_before=True)
```

2021-01-13 17:38 UTC, soupytwist commented on pasta/base/annotate.py
> +                       default=False):
```suggestion
    def optional_token(self, node, attr_name, token_val,
                       allow_whitespace_prefix=False, default=False):
```

2021-01-13 17:38 UTC, soupytwist commented on pasta/base/annotate_test.py
> +from typed_ast import ast27
`_ast` and `ast` imports -- still needed?

2021-01-14 18:56 UTC, bronevet-abc commented on pasta/augment/import_utils.py
> +    if py_ver < (3, 0):
Done. Added a method to return ast27 or ast3. Using it in all similar code.

2021-01-14 18:56 UTC, bronevet-abc commented on pasta/augment/import_utils.py
> +    if isinstance(node, (ast27.alias, ast3.alias)):
Couldn't think of anything clean

2021-01-14 20:44 UTC, bronevet-abc commented on pasta/augment/import_utils_test.py
> +  """
Done

2021-01-14 20:49 UTC, bronevet-abc commented on pasta/augment/rename.py
> +def rename_external(t, old_name, new_name, py_ver):
Done

2021-01-14 20:50 UTC, bronevet-abc commented on pasta/augment/rename.py
> +  sc = scope.analyze(t, py_ver)
Done

2021-01-14 20:53 UTC, bronevet-abc commented on pasta/base/ast_utils.py
>  import ast
Done

2021-01-15 01:16 UTC, soupytwist approved these changes

2021-01-15 16:28 UTC, merged